import type { Project } from "./types";

export const fluidsSimulator: Project = {
    slug: "fluids-simulator",
    name: "Fluids simulator",
    year: 2025,
    blurb: "Fluids simulator with blobby modeling (metaballs) and spring mechanics. Advanced graphics course final project, NCSU.",
    image: "/projects/metaball_fluids/metaball_fluids_01.png",
    alt: "Fluids simulator",
    focal: "75% center",
    links: [
        {
            label: "Demo video",
            href: "https://ecjonson.github.io/MetaballFluids/demo.mp4",
            title: "Recorded walkthrough of the simulator (MP4)",
        },
        {
            label: "Interactive tool",
            href: "https://ecjonson.github.io/MetaballFluids/",
            title: "Run the simulator in your browser — WebGL 1.0",
            desktopOnly: true,
        },
        {
            label: "GitHub",
            href: "https://github.com/ecjonson/MetaballFluids",
            title: "Source code — rendering, shading, physics and interface",
        },
    ],
    sections: [
        {
            id: "overview",
            label: "Overview",
            heading: "Metaball fluids with marching cubes",
            body: "I combined blobby modeling (metaballs) with spring-based physics to generate a fluid surface mesh that melds and deforms in real time.",
            image: "/projects/metaball_fluids/metaball_fluids_01.gif",
            alt: "Animated metaball fluid melding and deforming in the simulator.",
            focal: "right center",
            animated: true,
        },
        {
            id: "mesh",
            label: "The Mesh Algorithm",
            heading: "Metaballs with marching cubes",
            body: "Metaballs, also called blobby objects, are implicit isosurfaces that meld together as they approach one another. I polygonize them into a renderable mesh with marching cubes, then apply all sorts of fun rendering and physics techniques.",
            image: "/projects/metaball_fluids/metaball_fluids_04.png",
            alt: "Metaball surface from the simulator.",
        },
        {
            id: "physics",
            label: "The Physics",
            heading: "Spring mechanics",
            body: "A particle system governed by a network of springs, that push and pull on one another, make a tunable sandbox-style physics playground.",
            image: "/projects/metaball_fluids/metaball_fluids_02.png",
            alt: "Particle physics visualized in the simulator.",
            focal: "left bottom",
        },
        {
            id: "code",
            label: "Code",
            heading: "Implementation",
            body: "I implemented this from scratch in WebGL 1.0, everything from rendering and shading to the physics and interface. Check out my GitHub repository and run it in your browser!",
            image: "/projects/metaball_fluids/metaball_fluids_03.png",
            alt: "Rendered fluid from the simulator.",
            focal: "center bottom",
        },
        {
            id: "sandbox",
            label: "Sandbox",
            heading: "A mathematical playground",
            body: "Play with shading techniques and physics variables to create your own liquids, or crash your browser with particles.",
            image: "/projects/metaball_fluids/metaball_fluids_05.png",
            alt: "Simulator with many particles forming a fluid.",
        },
    ],
};