import type { Project } from "./types";

export const gmailAddon: Project = {
    slug: "gmail-addon",
    name: "InterAction+ for Gmail",
    year: 2023,
    blurb: "Senior design project with LexisNexis to extend their Outlook extension toolkit InterAction+ into Google Workspace.",
    image: "/projects/interaction_plus/posters_and_pies_02.jpeg",
    alt: "Senior design posters and pies group photo 2023",
    focal: "center right",
    sections: [
        {
            id: "overview",
            label: "Overview",
            heading: "InterAction+ for Gmail",
            body: "We teamed up with LexisNexis to design and build a Gmail add-on based on InterAction+, their Outlook CRM extension for legal professionals.",
            image: "/projects/interaction_plus/login.png",
            alt: "Low-level design of the login screen in the Gmail add-on.",
            focal: "center right",
            size: "LG",
        },
        {
            id: "role",
            label: "My role",
            heading: "My role",
            body: "Design, project staging, and implementation. I worked on the high-level designs in Balsamiq, staged the project for effective team collaboration, and wrote much of the code in Google Apps Script.",
            image: "/projects/interaction_plus/posters_and_pies_01.jpeg",
            alt: "Evan Jonson at the senior design posters and pies event, 2023.",
            focal: "center top",
            size: "SM",
        },
        {
            id: "design",
            label: "Design",
            heading: "The design",
            body: "We mapped every screen and flow in Balsamiq before we touched code, starting with authentication, how a user securely connects the add-on to their InterAction+ account from inside Gmail.",
            image: "/projects/interaction_plus/design_01.png",
            alt: "Authentication flow diagram of our Gmail add-on.",
        },
        {
            id: "architecture",
            label: "Architecture",
            heading: "System architecture",
            body: "The add-on had to bridge Gmail, Google Apps Script, and the InterAction+ backend. This diagram lays out how those pieces talk to each other and where data moves between them.",
            image: "/projects/interaction_plus/design_02.png",
            alt: "System architecture diagram of our Gmail add-on.",
            size: "LG",
        },
        {
            id: "staging",
            label: "Staging",
            heading: "Project staging",
            body: "To keep a student team building in parallel, I broke the work into staged, dependency-ordered tasks in a shared JSON, so everyone always knew what was unblocked and ready to pick up next.",
            image: "/projects/interaction_plus/staging_01.png",
            alt: "Project staging JSON file.",
            focal: "center left",
        },
        {
            id: "implementation",
            label: "Implementation",
            heading: "Google Apps Script",
            body: "We built the add-on in Google Apps Script, Google's platform for extending Workspace. Here it's open to a contact's sender details, surfacing their InterAction+ relationship data right beside the email.",
            image: "/projects/interaction_plus/sender_details.png",
            alt: "Our add-on open to a contact's sender details page.",
            focal: "center right",
            size: "LG",
        },
        {
            id: "reflection",
            label: "Reflection",
            heading: "Reflection",
            body: "This project taught me how careful design and disciplined task staging matter when a team is shipping against an unfamiliar platform on a deadline, and was a fun exercise on overcoming framework limitations.",
        },
    ],
};
