import type { Project } from "./types";

export const pathtracing: Project = {
    slug: "pathtracing",
    name: "Path tracer",
    year: 2025,
    blurb: "A physically-based path tracer written from scratch in WebGL 1.0, rendering the Cornell box. Advanced graphics course project, NCSU.",
    image: "/projects/pathtracing/cornell_box_01.png", // final / converged render (hero)
    alt: "Path-traced Cornell box, fully converged.",
    focal: "center",
    sections: [
        {
            id: "overview",
            label: "Overview",
            heading: "Light, simulated",
            body: "I built a Monte Carlo path tracer from scratch, no engine, no ray-tracing library, and pointed it at a version of Cornell box wih spheres. Path tracing simulates light in reverse: rays leave the camera, bounce randomly around the room, and gather the light they find. Averaging many samples per pixel produces a physically accurate image.",
            image: "/projects/pathtracing/cornell_box_02.png",
            alt: "Early Cornell box render, noisy with only a few samples per pixel.",
            size: "LG",
        },
        {
            id: "gi",
            label: "Global illumination",
            heading: "Color bleeding",
            body: "Light bouncing off the red and blue walls tints the white surfaces nearby. That subtle color bleed is indirect lighting, the effect that only global illumination, not traditional direct lighting, can reproduce.",
            image: "/projects/pathtracing/cornell_box_01.png",
            alt: "Cornell box render showing color bleeding from the red and green walls.",
            size: "LG",
        },
        {
            id: "convergence",
            label: "Convergence",
            heading: "Thousands of samples later",
            body: "Monte Carlo noise falls off slowly, the finished image is the average of thousands of light paths per pixel. What's left is soft shadows, smooth gradients, and clean indirect light.",
            image: "/projects/pathtracing/cornell_box_03.png",
            alt: "Nearly noise-free, converged Cornell box render.",
            size: "LG",
        },
        {
            id: "oops",
            label: "Oops",
            heading: "Pretty bugs",
            body: "Writing a renderer from scratch means breaking it in visually spectacular ways. A few of my favorite failures...",
        },
        {
            id: "bug-fireflies",
            label: "Bug",
            heading: "Fireflies",
            body: "High-variance samples divided by a near-zero probability blow up into bright specks scattered across the frame. Mathematically wrong, weirdly starry.",
            image: "/projects/pathtracing/cornell_box_07.png",
            alt: "Cornell box render peppered with bright firefly noise.",
            size: "LG",
        },
        {
            id: "bug-leak",
            label: "Bug",
            heading: "Light leak",
            body: "A missing clamp let energy escape through the walls, washing the whole scene in an impossible, dreamy glow.",
            image: "/projects/pathtracing/cornell_box_04.png",
            alt: "Cornell box render with light leaking through the walls.",
            size: "LG",
        },
        {
            id: "bug-plaid",
            label: "Bug",
            heading: "Plaid",
            body: "An error in spacial sample frequency. A scene split into an even grid of squares, each converging at its own pace.",
            image: "/projects/pathtracing/cornell_box_06.png",
            alt: "Cornell box render with a plaid grid pattern, each square converging at a different rate.",
            size: "LG",
        },
        {
            id: "reflection",
            label: "Reflection",
            heading: "My experience",
            body: "Building a path tracer bottom-up made the rendering equation click in a way no lecture could, and the bugs were half the fun. Next time I'd reach for WebGL 2.0 or WebGPU to escape the 1.0 constraints.",
        },
    ],
};
